### ISSUE TITLE
Segfault when using macros via REPL

### ISSUE THREAD

**Issue by K4rakara** [pigpigyyy/Yuescript#40]
Typing in the following code (or any other macro I've tried) into the REPL causes a segmentation fault on Linux:
```moonscript
macro name_of = (ident) -> "\"#{ident}\""
$name_of hi
```

**Comment by pigpigyyy** [comment]
How you are using the Yuescript binary tool? Through `luarocks install yuescript` or `make release`? And what version of Yuescript and Lua are you using? The version of Yuescript 0.6.9 works fine with Lua 5.4 on my Linux environment. So I need more info to reproduce the problem.

**Comment by K4rakara** [comment]
I'm using the luarocks version, yuescript 0.6.6, and lua 5.4 on Arch Linux.

**Comment by pigpigyyy** [comment]
It should be the issue of older Yuescript. Try `luarocks install yuescript` again should fix the problem.

**Comment by K4rakara** [comment]
Just updated to 0.6.9, but the issue still persists for all macros. :thinking:

**Comment by pigpigyyy** [comment]
How about using the makefile with `make release` in the project folder to build the tool with builtin Lua.

**Comment by K4rakara** [comment]
Sorry for the delay-- I'm still getting the segmentation fault with `make release`. 

Also--

This works:
```sh
> $
macro some_macro = (name) -> "\"#{name}\""
$some_macro HI
> $
```

This doesn't:
```sh
> macro some_macro = (name) -> "\"#{name}\""
> $some_macro HI
```

**Comment by pigpigyyy** [comment]
Tested on archlinux with glibc 2.33 and located the problem, it is a bug in the compiler. And the minimal example to reproduce the issue is
```moonscript
global *
$f!
```
The problem should be fixed by newest commit.
